blockExoticSubdeps: false

minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.104'
  - '@ai-sdk/openai-compatible@3.0.63'
  - '@ai-sdk/provider-utils@5.0.54'
  - '@ai-sdk/provider@4.0.22'
  - '@ai-sdk/vue@4.0.128'
  - '@iconify-json/lucide@1.2.140'
  - ai@7.0.128

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - semver@5.7.2
  - undici-types@6.21.0

nodeLinker: hoisted
shellEmulator: true

allowBuilds:
  esbuild: true
  uiohook-napi: true
  vue-demi: true
